#### 1. ตรวจสอบว่ามี library ของ numpy ถูกติดตั้งอยู่หรือไม่

In [ ]:
! pip show numpy

#### 2. ถ้ายังไม่ได้ติดตั้งให้ทำการติดตั้ง library ของ numpy โดยใช้คำสั่ง

In [ ]:
! pip install numpy

#### 3. การสร้าง Array ใน numpy สามารถทำได้โดยใช้คำสั่ง np.array()

In [11]:
import numpy as np

# อาเรย์แบบ scalar
a = np.array(10)
print(a)

# อาเรย์แบบ vector
row = np.array([1, 2, 3]) # 1 row 3 columns
column = np.array([[1], [2], [3]]) # 3 rows 1 column

print(row)
print(column)

# อาเรย์แบบ matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # 2 rows 3 columns
print(matrix)

10
[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [4 5 6]]


#### 4. การสร้างตัวเลขแบบสุ่มใน numpy สามารถทำได้โดยใช้คำสั่ง np.random

In [63]:
# ตัวอย่างการ random เลขจำนวนเต็ม 0-9 ขนาด 5 ตัว
r1 = np.random.randint(0, 10, 5) # vector 1 row 5 columns
print(r1)

# Random เลขทศนิยม 0-1
r2 = np.random.random(5) # vector 1 row 5 columns
print(r2)

[4 1 5 6 6]
[0.10147969 0.49208445 0.82598234 0.16246971 0.43851692]


#### 5. การเข้าถึงและเลือกสมาชิกใน Array สามารถทำได้โดยใช้คำสั่ง

In [69]:
vrow = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # 1 row 10 columns

print(vrow) # แสดงค่าทั้งหมด
print(vrow[3]) # แสดงค่าตำแหน่งที่ 3
print(vrow[2:6]) # แสดงค่าตำแหน่งที่ 2-6
print(vrow[:5]) # แสดงค่าตำแหน่งที่ 0-5
print(vrow[5:]) # แสดงค่าตำแหน่งที่ 5-จบ
print(vrow[-3:-1]) # แสดงค่าตำแหน่งที่ 1 ตัวสุดท้าย

[ 1  2  3  4  5  6  7  8  9 10]
4
[3 4 5 6]
[1 2 3 4 5]
[ 6  7  8  9 10]
[8 9]


#### 6. การหาค่าทางสถิติใน numpy สามารถทำได้โดยใช้คำสั่ง

In [78]:
stat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # 3 rows, 4 columns
print(stat)

# การหาค่าสูงสุด
print("Max:", np.max(stat))

# การหาค่าต่ำสุด
print("Min:", np.min(stat))

# การหาค่าเฉลี่ย
print("Mean:", np.mean(stat))

# การหาค่ามัธยฐาน (ค่ากลาง)
print("Median:", np.median(stat))

# การหาค่าส่วนเบี่ยงเบนมาตรฐาน
print("Standard Deviation:", np.std(stat))

# หาค่าความแปรปรวน (variance)
print("Variance:", np.var(stat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max: 12
Min: 1
Mean: 6.5
Median: 6.5
Standard Deviation: 3.452052529534663
Variance: 11.916666666666666
